DROP TABLE AUTO;

CREATE TABLE AUTO(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    PRECIO NUMBER,
    COLOR NVARCHAR2(100)
);

INSERT INTO AUTO VALUES(1, 'BEATLE', 'VOLSVAGEN', 35000, 'AZUL');
COMMIT;

SELECT * FROM AUTO;


CREATE TABLE REFRESCO(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    PRECIO NUMBER,
    CONTENIDO NUMBER
);

INSERT INTO REFRESCO VALUES(1, 'COCA-COLA', 'COCOA-COLA', 10, 400);
COMMIT;

SELECT * FROM REFRESCO;