CREATE TABLE APIMARCA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100) UNIQUE,
    SLOGAN NVARCHAR2(100)
);

CREATE TABLE APIPAIS(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100) UNIQUE,
    CONTINENTE NUMBER CHECK(CONTINENTE IN (1,2,3,4,5))
);

CREATE TABLE APIGALLETA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100) UNIQUE,
    ID_MARCA NUMBER,
    PRECIO NUMBER,
    CONTE_NETO NUMBER,
    SABOR NVARCHAR2(100),
    ID_PAIS NUMBER,
    FOREIGN KEY (ID_MARCA) REFERENCES APIMARCA(ID),
    FOREIGN KEY (ID_PAIS) REFERENCES APIPAIS(ID)
);

DROP TABLE APIGALLETA;

SELECT * FROM APIMARCA;
DELETE FROM APIMARCA;
INSERT INTO APIMARCA(NOMBRE, SLOGAN) VALUES('LARA', 'RICAS GALLETAS');

DELETE FROM APIPAIS;
SELECT * FROM APIPAIS;
INSERT INTO APIPAIS(NOMBRE, CONTINENTE) VALUES('USA', 1);

DELETE FROM APIGALLETA;
INSERT INTO APIGALLETA(NOMBRE, ID_MARCA, PRECIO, CONTE_NETO, SABOR, ID_PAIS) VALUES('MARIAS', 1, 20, 200, 'VAINILLA', 1);
COMMIT;

CREATE SEQUENCE MARCA_SECUENCIA;
CREATE SEQUENCE PAIS_SECUENCIA;
CREATE SEQUENCE GALLETA_SECUENCIA;

CREATE OR REPLACE TRIGGER INCREMENT_ID_MARCA
BEFORE INSERT ON APIMARCA
FOR EACH ROW

BEGIN
    SELECT MARCA_SECUENCIA.nextval
    INTO :NEW.ID
    FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INCREMENT_ID_PAIS
BEFORE INSERT ON APIPAIS
FOR EACH ROW

BEGIN
    SELECT PAIS_SECUENCIA.nextval
    INTO :NEW.ID
    FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INCREMENT_ID_GALLETA
BEFORE INSERT ON APIGALLETA
FOR EACH ROW

BEGIN
    SELECT GALLETA_SECUENCIA.nextval
    INTO :NEW.ID
    FROM DUAL;
END;