CREATE TABLE APIPADRE(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    APM NVARCHAR2(100),
    FECHA_NAC DATE
);

DROP TABLE APIHIJO;
CREATE TABLE APIHIJO(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    APM NVARCHAR2(100),
    HOBBY NVARCHAR2(100),
    ID_PADRE NUMBER,
    FOREIGN KEY (ID_PADRE) REFERENCES APIPADRE(ID)
);

DELETE FROM APIPADRE;
INSERT INTO APIPADRE VALUES(1, 'GOKU', 'SON', 'KAKAROTO', '16-10-1988');

INSERT INTO APIHIJO VALUES(1, 'GOHAN', 'SON', 'OCCSATAN', 'ESTUDIAR', 1);
COMMIT;