SELECT * FROM PELICULAAPI;

CREATE TABLE PELICULAAPI(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    GENERO NVARCHAR2(100),
    DURACION NVARCHAR2(100)
);

INSERT INTO PELICULAAPI VALUES(1, 'TITANIC', 'DRAMA', '2hrs');
COMMIT;