select * from POKEMON;
DELETE FROM POKEMON WHERE ID = 0;
COMMIT;

CREATE TABLE POKEMON(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    PREEVOLUCION NVARCHAR2(100),
    EVOLUCION NVARCHAR2(100),
    TIPO NVARCHAR2(100),
    NIVELPODER NUMBER
);

INSERT INTO POKEMON VALUES(1, 'PIKACHU', 'PICHU', 'RAYCHU', 'ELECTRICO', 100);
COMMIT;

DROP TABLE POKEMON;