CREATE TABLE CATEGORIASA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100)
);

INSERT INTO CATEGORIASA VALUES(1, 'LACTEOS');
INSERT INTO CATEGORIASA VALUES(2, 'PAN');

SELECT * FROM CATEGORIASA;

CREATE TABLE PRODUCTOSA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    PRECIO NUMBER,
    CONTENIDO_NETO NUMBER,
    ID_CATEGORIA NUMBER,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIASA(ID)
);

INSERT INTO PRODUCTOSA VALUES(1, 'ALPURA', 20, 100, 1);
COMMIT;

SELECT * FROM productosa;