--QUERY REALIZADO EN ORACLE POR ROGELIO GONZÁLEZ SÁNCHEZ
DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APP NVARCHAR2(100),
    APM NVARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    CELULAR NVARCHAR2(10),
    CORREO NVARCHAR2(100)
);

CREATE SEQUENCE INCRE_CLIENT;

CREATE OR REPLACE TRIGGER AUTO_INCREMENT
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    SELECT INCRE_CLIENT.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;

INSERT INTO CLIENTE(NOMBRE, APP, APM,FECHA_NACIMIENTO, CELULAR, CORREO) VALUES('JORGE', 'RODRIGUEZ', 'BUSTAMANTE', '24/02/1984', '2384516781', 'jorobu@gmail.com');
INSERT INTO CLIENTE(NOMBRE, APP, APM,FECHA_NACIMIENTO, CELULAR, CORREO) VALUES('SAMANTHA', 'PEREZ', 'ADAN', '12/10/1994', '2381442564', 'sapead@gmail.com');

UPDATE CLIENTE SET CORREO = 'samthperada@gmail.com' WHERE ID = 2;

DELETE FROM CLIENTE WHERE ID = 2;

SELECT * FROM CLIENTE;