SELECT * FROM PRODUCTO15;
SELECT * FROM BIT_PRODUCTO15;

INSERT INTO PRODUCTO15 VALUES(1, 'MAYONESA', 50, 'MCORMIC');
INSERT INTO PRODUCTO15 VALUES(2, 'TV', 10000, 'SAMSUNG');
INSERT INTO PRODUCTO15 VALUES(10, 'SABRITAS', 20, 'BARCEL');
INSERT INTO PRODUCTO15 VALUES(12, 'LAPTOP', 16000, 'ACER');

DELETE FROM PRODUCTO15 WHERE ID =1;

UPDATE PRODUCTO15 SET PRECIO = 24000 WHERE ID = 12;


CREATE TABLE ANIMAL(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    ESPECIE NVARCHAR2(100)
);

CREATE TABLE BITACORA(
    ID NUMBER PRIMARY KEY,
    ID_ANIMAL NUMBER,
    NOMBRE NVARCHAR2(100),
    ESPECIE NVARCHAR2(100),
    NOMBRE_OLD NVARCHAR2(100),
    ESPECIE_OLD NVARCHAR2(100),
    ACCION NVARCHAR2(100),
    USUARIO NVARCHAR2(100),
    FECHA DATE
);

DROP TABLE BITACORA;

ALTER TABLE BITACORA ADD ACCION NVARCHAR2(100);
ALTER TABLE BITACORA ADD USUARIO NVARCHAR2(100);
ALTER TABLE BITACORA ADD FECHA DATE;

SELECT * FROM ANIMAL;
SELECT * FROM BITACORA;

INSERT INTO ANIMAL VALUES(1, 'GATO', 'FELINO');
INSERT INTO ANIMAL VALUES(2, 'PERRO', 'CANINO');
INSERT INTO ANIMAL VALUES(3, 'LEON', 'FELINO');
INSERT INTO ANIMAL VALUES(4, 'LORO', 'AVE');

DELETE FROM ANIMAL WHERE ID = 3;

DELETE FROM ANIMAL WHERE ID = 4;

UPDATE ANIMAL SET NOMBRE = 'LOBO' WHERE ID = 2;

UPDATE ANIMAL SET NOMBRE = 'GUACAMAYA' WHERE ID = 4;

create or replace TRIGGER INSERT_BITACORA
AFTER INSERT ON ANIMAL
FOR EACH ROW
DECLARE
ID_B INT;
FECHA_B DATE;
USUARIO VARCHAR(50);
BEGIN

    SELECT MAX(ID+1) INTO ID_B FROM BITACORA;
    SELECT SYSDATE INTO FECHA_B FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    IF(ID_B IS NULL) THEN
    ID_B :=1;
    END IF;

    INSERT INTO BITACORA VALUES(ID_B, :NEW.ID, :NEW.NOMBRE, :NEW.ESPECIE, NULL, NULL, 'INSERT', USUARIO, FECHA_B);
END;

create or replace TRIGGER DELETE_BITACORA
AFTER DELETE ON ANIMAL
FOR EACH ROW
DECLARE
ID_B INT;
FECHA_B DATE;
USUARIO VARCHAR(50);
BEGIN

    SELECT MAX(ID+1) INTO ID_B FROM BITACORA;
    SELECT SYSDATE INTO FECHA_B FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    IF(ID_B IS NULL) THEN
    ID_B :=1;
    END IF;

    INSERT INTO BITACORA VALUES(ID_B, :OLD.ID, :NEW.NOMBRE, :NEW.ESPECIE, NULL, NULL, 'DELETE', USUARIO, FECHA_B);
END;

create or replace TRIGGER UPDATE_BITACORA
AFTER UPDATE ON ANIMAL
FOR EACH ROW
DECLARE
ID_B INT;
FECHA_B DATE;
USUARIO VARCHAR(50);
BEGIN

    SELECT MAX(ID+1) INTO ID_B FROM BITACORA;
    SELECT SYSDATE INTO FECHA_B FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    IF(ID_B IS NULL) THEN
    ID_B :=1;
    END IF;

    INSERT INTO BITACORA VALUES(ID_B, :NEW.ID, :NEW.NOMBRE, :NEW.ESPECIE, :OLD.NOMBRE, :OLD.ESPECIE, 'UPDATE', USUARIO, FECHA_B);
END;

create or replace TRIGGER INSERT_UPDATE_DELETE_BITACORA
AFTER INSERT OR UPDATE OR DELETE ON ANIMAL
FOR EACH ROW
DECLARE
ID_B INT;
FECHA_B DATE;
USUARIO VARCHAR(50);
BEGIN

    SELECT MAX(ID+1) INTO ID_B FROM BITACORA;
    SELECT SYSDATE INTO FECHA_B FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    IF(ID_B IS NULL) THEN
    ID_B :=1;
    END IF;
    
    IF INSERTING THEN INSERT INTO BITACORA VALUES(ID_B, :NEW.ID, :NEW.NOMBRE, :NEW.ESPECIE, NULL, NULL, 'INSERT', USUARIO, FECHA_B); END IF;
    IF UPDATING THEN INSERT INTO BITACORA VALUES(ID_B, :NEW.ID, :NEW.NOMBRE, :NEW.ESPECIE, :OLD.NOMBRE, :OLD.ESPECIE, 'UPDATE', USUARIO, FECHA_B); END IF;
    IF DELETING THEN INSERT INTO BITACORA VALUES(ID_B, :OLD.ID, :OLD.NOMBRE, :OLD.ESPECIE, NULL, NULL, 'DELETE', USUARIO, FECHA_B); END IF;
END;