/*
    MARCA_COMPUTADORAS -> ID, NOMBRE, PAIS
    COMPUTADORAS -> ID, MODELO, ID_MARCA, PRECIO, RAM
*/


CREATE TABLE MARCA_COMPUTADORA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    PAIS NVARCHAR2(100)
);

CREATE TABLE COMPUTADORA(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(100),
    ID_MARCA NUMBER,
    PRECIO NUMBER,
    RAM NUMBER,
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA_COMPUTADORA(ID)
);


INSERT INTO MARCA_COMPUTADORA VALUES(1, 'SAMSUNG', 'KOREA');

INSERT INTO COMPUTADORA VALUES(1, 'M1', 1, 20000, 5);
COMMIT;
SELECT * FROM MARCA_COMPUTADORA;
SELECT * FROM COMPUTADORA;

