CREATE TABLE API_GENERO(
  ID NUMBER PRIMARY KEY,
  NOMBRE NVARCHAR2(100),
  DESCRIPCION NVARCHAR2(100)
);

CREATE TABLE API_PAIS(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    CONTINENTE NUMBER
);

CREATE TABLE API_SERIE(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_GENERO NUMBER,
    CAPITULOS NUMBER,
    TEMPORADAS NUMBER,
    ID_PAIS NUMBER,
    FOREIGN KEY (ID_GENERO) REFERENCES API_GENERO(ID),
    FOREIGN KEY (ID_PAIS) REFERENCES API_PAIS(ID)
);

--3 IDIOTAS

SELECT * FROM API_GENERO;
INSERT INTO API_GENERO VALUES(1, 'AVENTURA', 'LA AVENTURA COMIENZA');

SELECT * FROM API_PAIS;
INSERT INTO API_PAIS VALUES(1, 'USA', 1);

SELECT * FROM API_SERIE;
INSERT INTO API_SERIE VALUES(1, 'MADE IN ABYSS', 1, 20, 2, 1);
COMMIT;

CREATE SEQUENCE INCRE_GENERO;
CREATE SEQUENCE INCRE_PAIS;
CREATE SEQUENCE INCRE_SERIE;

CREATE OR REPLACE TRIGGER INCRE_GENERO
BEFORE INSERT ON API_GENERO
FOR EACH ROW
BEGIN
    SELECT INCRE_GENERO.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INCRE_PAIS
BEFORE INSERT ON API_PAIS
FOR EACH ROW
BEGIN
    SELECT INCRE_PAIS.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INCRE_SERIE
BEFORE INSERT ON API_SERIE
FOR EACH ROW
BEGIN
    SELECT INCRE_SERIE.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;