CREATE TABLE TENNI(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    PRECIO NUMBER,
    NUM_INI NUMBER,
    NUM_FIN NUMBER
);

SELECT * FROM TENNI WHERE UPPER(MODELO) LIKE UPPER('%n%');

INSERT INTO TENNI VALUES(1, 'MNS1', 'JORDAR', 2000, 22, 30);
COMMIT;