CREATE TABLE VEGETALES(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    CALORIAS NUMBER,
    PRECIO NUMBER,
    COLOR NVARCHAR2(100)
);

INSERT INTO VEGETALES VALUES(1, 'PAPA', 200, 20, 'AMARILLO');
COMMIT;

SELECT * FROM VEGETALES;