CREATE TABLE VIDEOJUEGO(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    GENERO NVARCHAR2(100),
    PRECIO NUMBER
);

INSERT INTO VIDEOJUEGO VALUES(1, 'MARIO BROSS', 'NINTENDO', 'AVENTURA', 2000);
COMMIT;